# Generated by Django 3.2.16 on 2022-12-02 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='print_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piid', models.IntegerField()),
                ('qrcode', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=20)),
                ('extra1', models.BigIntegerField()),
                ('extra2', models.CharField(max_length=20)),
                ('extra3', models.CharField(max_length=20)),
                ('date_time', models.DateTimeField()),
                ('add_date', models.DateTimeField()),
                ('device_id', models.IntegerField()),
            ],
            options={
                'db_table': 'print_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='scan_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slave_id', models.IntegerField()),
                ('first_scan', models.CharField(max_length=50)),
                ('first_scan_datetime', models.DateTimeField()),
                ('air_pressure', models.CharField(max_length=50)),
                ('leak_rate', models.CharField(max_length=50)),
                ('ok_signal', models.CharField(max_length=10)),
                ('test_datetime', models.DateTimeField()),
                ('second_scan', models.CharField(max_length=50)),
                ('second_scan_datetime', models.DateTimeField()),
                ('device_id', models.CharField(max_length=50)),
                ('varient', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'scan_data',
                'managed': False,
            },
        ),
    ]
